### ISSUE TITLE
Can't setup reverse proxy with custom domain

### ISSUE THREAD

**Issue by diamant-x** [lildude/ha-addon-ghostfolio#15]
Hi again,

I'm playing around with the tool, and trying to set it up in my own nginx reverse proxy where i handle all my subdomains. However, trying to point to the container port, while the favicon and page title seems to work (so the proxy itself is correctly setup) seems like the container is blocking the connection, I get a white page. Dev console just shows a 'SyntaxError: Unexpected end of JSON input'

* Could you make it so that ingress can be enabled/disabled so that custom proxys can work?

The reason why i don't like ingress is because if i need to store usernames/passwords, like in ghostfolio, then my passwords managers just show it always that i am in home-assistant.

Also, i think due to this, whenever i 'log out' form my account in ghostfolio, it also logs me out from Home Assistant.
* Could you take a look at it as well?

Thanks.

**Comment by lildude** [comment]
> * Could you make it so that ingress can be enabled/disabled so that custom proxys can work?

Yeah, I think I know what's causing this:

https://github.com/lildude/ha-addon-ghostfolio/blob/e002ff78da1092f7f54c6645feaf5731cdf6b989/rootfs/etc/services.d/ghostfolio/run#L54C1-L57C3

If I'm right, I just need to put this behind a check to see if you've enabled the port option. I can probably also not start Nginx in this case too to save on resources.

I'll take a look at this in the next few days.

> Also, i think due to this, whenever i 'log out' form my account in ghostfolio, it also logs me out from Home Assistant.

This shouldn't be the case as I've not integrated the Ghostfolio auth with the Home Assistant auth. I do know you'll get a 404 as the redirect from the logout still needs some work when using ingress as it redirects to a path that isn't accessible.

**Comment by diamant-x** [comment]
> If I'm right, I just need to put this behind a check to see if you've enabled the port option.

It would be better to have it as a separate addon config option. Because my nginx reverse proxy sits in the same docker instance as ghostfolio, i can point it to the docker container name and internal port without the need to expose it through the home-assistance instance. This means i do NOT configure any port in the addon config screen for proxy to work.

**Comment by lildude** [comment]
Are you able to share your reverse proxy config so I can test it to be sure?

**Comment by diamant-x** [comment]
> Are you able to share your reverse proxy config so I can test it to be sure?

I use https://github.com/hassio-addons/addon-nginx-proxy-manager
Then in the GUI, i set up a proxy like:
![image](https://github.com/lildude/ha-addon-ghostfolio/assets/7346338/96f3a940-59f8-44b5-a181-1c8ee40aceee)
where the hostname matches the container ID found when running the addon:
![image](https://github.com/lildude/ha-addon-ghostfolio/assets/7346338/94e2b1a1-17cc-4643-b422-fed27a80706c)

**Comment by lildude** [comment]
Things should now work with the latest release. As noted in the [PR](https://github.com/lildude/ha-addon-ghostfolio/pull/16) body, you will need to enable and set the port mapping as it's a security risk exposing direct access to a port and I don't want to be responsible for the ill-informed shooting themselves in the foot.

**Comment by lildude** [comment]
An even better fix is in https://github.com/lildude/ha-addon-ghostfolio/pull/18 and removes all the hacking I was doing before. 


https://github.com/lildude/ha-addon-ghostfolio/pull/19 fixes the logout taking you to an invalid page and signing you out of HA.

**Comment by diamant-x** [comment]
Thanks! V1.4.1 works great and reverse proxy is perfect. Thank you.
