### ISSUE TITLE
Linked PostgreSQL Addon is no longer active

### ISSUE THREAD

**Issue by diamant-x** [lildude/ha-addon-ghostfolio#63]
Hi,

The addon for PostgreSQL you link in the requirements is no longer active and has been archived.
`For convenience, my [add-ons repository](https://github.com/lildude/ha-addons) includes configuration that points to the [PostgreSQL add-on](https://github.com/matt-FFFFFF/hassio-addon-postgres) so you can install everything from one repo.`
As a result Home Assistant flags it for removal from HAOS.

What addonn would you recommend to install instead?
Can you update the links for those?

Thanks!

**Comment by lildude** [comment]
I've just merged https://github.com/lildude/ha-addon-ghostfolio/pull/65 to update the recommendation to use https://github.com/alexbelgium/hassio-addons/tree/master/postgres

**Comment by diamant-x** [comment]
Hi,

I just had now the time to try to set it up. Unfortunately the new addon doesn't seem as straight forward.
I downloaded the new addon, set the variables of the psotgre addon to:
POSTGRES_PASSWORD: mypassword
POSTGRES_DB: ghostfolio
POSTGRES_USER: ghostfolio

I run the addon, and it fails to load with error "role ghostfolio doesn't exist".
I remove the postgres_user and leave it blank (which seems it would then be "postgres" https://hub.docker.com/_/postgres ).
Then addon loads fine.
I go to Ghostfolio addon. Set the above settings and start it. And then the connection fails.
In the Postgre logs I see "failed password authentication of user postgres".

Any idea how to set Ghostfolio up with this new DB addon in HAOS?

Thanks!

**Comment by lildude** [comment]
You should use the username and password you set according to the Postgres addon [configuration docs](https://github.com/alexbelgium/hassio-addons/tree/master/postgres#configuration).

> default user: `postgres` password: set by `POSTGRES_PASSWORD`

You can only use a different username if you've already created a new user in the database.

So if you're starting from scratch, 

1. in the Postgres addon config set `POSTGRES_PASSWORD`
2. start the Postgres addon
3. in the TeslaMate addon set the database username to `postgres`, the password to whatever you set in the addon, and the database hostname to `db21ed7f-postgres`
4. set the TeslaMate addon.

**Comment by diamant-x** [comment]
Got it. In fact my root issue was way easier: The addon creates a folder in "addon_config" with a parammetrization file of all enviornment variables, overwritting my UI ones. This folder survided addons uninstalls, so even after a new install my settings wouldn't apply.

I deleted the folder, installed again the addon, set the UI parameters I wanted (including DB user and DB name) and then started the postgre addon and it worked fine! :)

Thanks anyways for the prompt feedback!
