### ISSUE TITLE
Ghostfolio Addon crached

### ISSUE THREAD

**Issue by evertonbtm** [lildude/ha-addon-ghostfolio#74]
Hello,

After update 1.23.0    ghostfolio  2.107.1

Console show this log:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun ghostfolio (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
2024/09/15 10:31:21 [warn] 74#74: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
2024/09/15 10:31:21 [emerg] 74#74: mkdir() "/var/lib/nginx/body" failed (13: Permission denied)
[10:31:21] WARNING: Nginx crashed, halting add-on
[10:31:21] INFO: Nginx stopped, restarting...
s6-rc: info: service legacy-services: stopping
[10:31:22] INFO: Ghostfolio stopped, restarting...
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by lildude** [comment]
🤦 The upstream project hardened the dockerfile and whilst I updated the addon to take this into account for Ghostfolio, I forgot to do the same for Nginx.

Fixed in https://github.com/lildude/ha-addon-ghostfolio/pull/75

**Comment by evertonbtm** [comment]
Thank you my friend!
